name: Xinada
version: 1.0
author: Alcachofra
main: com.alcachofra.main.Xinada
api-version: 1.17
commands:
  start:
    description: Start a new game.
  next:
    description: Jump to next round.
  end:
    description: End the current game.
  role:
    description: See description for your role (in-game).